spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/supermarket_db
    username: user
    password: password123!

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
